name: blazebazzar
description: "A new Flutter project."
publish_to: 'none'
version: 2.5.1+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  flex_color_scheme: ^7.2.0
  gap: ^3.0.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shimmer_animation: ^2.1.0+1
  firebase_ui_auth: ^1.12.1
  country_state_city_picker: ^1.2.8
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_datepicker: ^25.1.37
  provider: ^6.1.1
  uuid: ^4.3.3
  photo_view: ^0.14.0
  flutter_slidable: ^3.0.1
  badges: ^3.1.2
  razorpay_flutter: ^1.3.6
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdf: ^25.1.37
  open_filex: ^4.4.0
  pdf: ^3.5.0
  downloads_path_provider_28: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/notoSans/NotoSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/notoSans/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/notoSans/NotoSans-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/notoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/notoSans/NotoSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/notoSans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/notoSans/NotoSans-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/notoSans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/notoSans/NotoSans-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/notoSans/NotoSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/notoSans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/notoSans/NotoSans-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/notoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/notoSans/NotoSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/notoSans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/notoSans/NotoSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/notoSans/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/notoSans/NotoSans-ThinItalic.ttf
          weight: 100
